# Assignment PIAIC (AIC) Batch 6

## Name: Umar Qayyum

## Roll no. PIAIC80346


### ASSIGNMENT 1

In [1]:
import numpy as np

In [2]:
# method 1
m1 = np.array([2,3,4])
print(m1)

[2 3 4]


In [3]:
# method 2
m2 = np.arange(6)  # 1d array
print(m2)

[0 1 2 3 4 5]


In [4]:
# method 3
m3 = np.arange(12).reshape(4,3) #2d array
print(m3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
# method 4
m4 = np.arange(24).reshape(2,3,4) #3d array
print(m4)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
# method 5
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
A * B  #elementwise product

array([[2, 0],
       [0, 4]])

In [7]:
#method 6
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
A @ B #matrix product

array([[5, 4],
       [3, 4]])

In [8]:
# method 7
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
A.dot(B)  #another matrix product

array([[5, 4],
       [3, 4]])

In [9]:
# method 8
rg = np.random.default_rng(1)     # create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
print(a)

[[3 3 3]
 [3 3 3]]


In [10]:
# method 9
rg = np.random.default_rng(1)   
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
b += a
b

array([[1.51182162, 1.9504637 , 1.14415961],
       [1.94864945, 1.31183145, 1.42332645]])

In [11]:
#method 10
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [12]:
# method 11
a = rg.random((2,3))
a.sum()

2.412007822394087

In [13]:
# method 12
a = rg.random((2,3))
a.min()

0.20345524067614962

In [14]:
# method 13
a = rg.random((2,3))
a.max()

0.9699254132161326

In [15]:
# method 14
b = np.arange(12).reshape(3,4)
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [16]:
# method 15
b = np.arange(12).reshape(3,4)
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [17]:
# method 16
b = np.arange(12).reshape(3,4)
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [18]:
#method 17
B = np.arange(3)
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [19]:
#method 18
B = np.arange(3)
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [20]:
#method 19
B = np.arange(3)
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [21]:
# method 20
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [22]:
# method 21
a = np.arange(10)**3
a[2]

8

In [23]:
# method 22
a = np.arange(10)**3
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [24]:
# method 23
a = np.arange(10)**3
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [25]:
# method 24
a = np.arange(10)**3
a[ : :-1]                                 # reversed a

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [26]:
# method 25
a = np.arange(10)**3
for i in a:
    print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [27]:
# method 26
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [28]:
# method 27
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c.shape

(2, 2, 3)

In [29]:
# method 28
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [30]:
# method 29
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [31]:
# method 30
a = np.floor(10*rg.random((3,4)))
a

array([[5., 1., 6., 7.],
       [6., 9., 0., 5.],
       [4., 0., 6., 8.]])

In [32]:
# method 31
a = np.floor(10*rg.random((3,4)))
a.ravel()  # returns the array, flattened

array([5., 2., 8., 5., 5., 7., 1., 8., 6., 7., 1., 8.])

In [33]:
# method 32
a = np.floor(10*rg.random((3,4)))
a.reshape(6,2)  # returns the array with a modified shape

array([[1., 0.],
       [8., 8.],
       [8., 4.],
       [2., 0.],
       [6., 7.],
       [8., 2.]])

In [34]:
# method 33
a = np.floor(10*rg.random((3,4)))
a.T  # returns the array, transposed

array([[2., 1., 5.],
       [6., 4., 0.],
       [8., 8., 6.],
       [9., 4., 9.]])

In [35]:
# method 34
a = np.floor(10*rg.random((3,4)))
a.T.shape

(4, 3)

In [37]:
# method 35
a = np.floor(10*rg.random((3,4)))
a.resize((2,6))
a

array([[8., 6., 8., 3., 5., 1.],
       [9., 2., 2., 0., 2., 7.]])

In [40]:
#method 36
a = np.floor(10*rg.random((2,2)))
a

array([[1., 2.],
       [2., 3.]])

In [41]:
#method 37
a = np.floor(10*rg.random((2,2)))

b = np.floor(10*rg.random((2,2)))
np.vstack((a,b))

array([[3., 5.],
       [9., 7.],
       [7., 7.],
       [5., 9.]])

In [42]:
#method 38
a = np.floor(10*rg.random((2,2)))

b = np.floor(10*rg.random((2,2)))
np.hstack((a,b))

array([[6., 5., 2., 1.],
       [0., 4., 5., 7.]])

In [43]:
# method 39
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [44]:
# method 40
a = np.arange(6).reshape(2,3) + 10
np.argmax(a)

5

In [45]:
# method 41
a = np.arange(6).reshape(2,3) + 10
np.argmax(a, axis=0)

array([1, 1, 1], dtype=int64)

In [46]:
# method 42
a = np.arange(6).reshape(2,3) + 10
np.argmax(a, axis=1)

array([2, 2], dtype=int64)

In [47]:
# method 43
a = np.arange(6).reshape(2,3) + 10
ind = np.unravel_index(np.argmax(a, axis=None), a.shape)
ind

(1, 2)

In [48]:
# method 44
x = np.array([[4,2,3], [1,0,3]])
index_array = np.argmax(x, axis=-1)
# Same as np.max(x, axis=-1, keepdims=True)
np.take_along_axis(x, np.expand_dims(index_array, axis=-1), axis=-1)

array([[4],
       [3]])

In [49]:
# method 45
a = np.array([[1,4],[3,1]])
np.sort(a)                # sort along the last axis

array([[1, 4],
       [1, 3]])

In [50]:
# method 46
a = np.array([[1,4],[3,1]])
np.sort(a, axis=None)     # sort the flattened array

array([1, 1, 3, 4])

In [51]:
#method 47
a = np.array([[1,4],[3,1]])
np.sort(a, axis=0)        # sort along the first axis

array([[1, 1],
       [3, 4]])

In [52]:
#method 48
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)       # create a structured array
np.sort(a, order='height')  

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [53]:
#method 49
x = np.array([[4, 9, 2, 10],
              [6, 9, 7, 12]])
np.ptp(x, axis=1)

array([8, 6])

In [54]:
#method 50
y = np.array([[1, 127],
              [0, 127],
              [-1, 127],
              [-2, 127]], dtype=np.int8)
np.ptp(y, axis=1)

array([ 126,  127, -128, -127], dtype=int8)